"""
Clean temporary files generated by PySCF is specified dir
"""
function clean_tmp_file(;dir="./")
    files = filter(file->startswith(file, "tmp"), readdir(dir))
    rm.(joinpath.(Ref(dir), files))
    nothing
end
