function generate_molden(ζ::ROHFState, filename::String)
    pyscf.tools.molden.from_mo(ζ.Σ.mol, filename, ζ.Φ)
    nothing
end

"""
Clean temporary files generated by PySCF is specified dir
"""
function clean_tmp_file(;dir="./")
    files = filter(file->startswith(file, "tmp"), readdir(dir))
    rm.(joinpath.(Ref(dir), files))
    nothing
end
